### ISSUE TITLE
First Org Meeting

### ISSUE THREAD

**Issue by ababaian** [hackseq/hackseqRNA#1]
Hey @hackseq/steering_committee_2016 @hackseq/steering_committee @hackseq/hs18_org @hackseq/hs19_organizers ,

With `hackseq19` done and successful, time to plan for `hackseqRNA`. In brief, we are teaming up with the [RNA Society](https://www.rnasociety.org/conferences/rna-2020/) and the Vancouver 2020 conference which is bringing 1000s of world-class RNA biologists to Vancouver. There is a great bioinformatics community there, so we will aim to bring international and local talent together.

[Please fill out the poll here](https://dudle.inf.tu-dresden.de/hsRNA/).
Add any ideas or discussion points below. 
Join the [organization team here](https://github.com/orgs/hackseq/teams/hackseqrna_org)

**Tentative Dates May 22 - 24, 2020**

## Agenda
- Introductions

### Organizational
- [x] Initiate Organizing Committee / Roles

### Logistics
- [ ] Find / Scout a location
- LSI Atrium is likely unavailable
- Consider conference centre downtown where RNA Society Meeting is taking place
- [SFU Harbour Centre](http://www.sfu.ca/mecs/vancouver-main/harbour-centre.html)
- [UBC Robson Square](https://robsonsquare.ubc.ca/event-conference-planning/entry/13/)
- Four Seasons or another hotel atrium

- [x] Discuss Format Guidelines
- 3 Days, possibly include later work hours if we secure another venue

### Team Leader
- [ ] Create an updated webpage/document on 'Why you should run a project', 'What is the scope of a project', 'FAQ for team leaders'.
- [ ] Create a list of RNA team leaders to head-hunt, scout out people who will know and/or can suggest team leaders.

### Funding
- [ ] Update funding schemes
- [ ] Create new 'Sponsor Info Document' to make an 'infographic' of what they get / what we're about.
- [ ] Developing World travel fund ( taken up from Kristen / Adriana )

# Minutes
## Roles
- Justin -Sponsor/financing
  - 2 others one to research, one for contacting
- Alex and Emre 
  - Team Lead hunting
- Artem
  - webmaster
- Emre - Tech

## Funding
- new sponsorship package
- what is most important thing they want
  - interested in table
  - industry lunch
- old sponsors - higher tier for both 
- American sponsors
- aim to get industries to run a project
- [x] Justin to start an issue

## Website
- edit for scope of project
- what is a hackathon
- what is the outcome
- FAQ - how to be a TL, participant, Sponsor etc
- publications coming out of hackseq
- something personal

## Location
- **deadline:** Dec. 10th
- possibly a hotel
  - atrium
  - possibility for hours to go longer
- [x] Justin -  SFU harbour centre 
- [x] **Jenny**
  - UBC at Robson Square
 - Hotel logistics 
- internet connection set-up
- Artem - to get Jenny into contact with RNA contact

## Format
- aiming for ~ 80 people, 10 teams (88 people + organizers)
- target Post Docs, Grad students, Scientists - less undergrad
  - want more experienced people
  - what experience can you demonstrate
- RNA based projects

## TL recruitment
- headhunt big labs that are going/in Vancouver
- make spreadsheet 
- [ ] **Artem** to upload abstracts from last year
- [ ] **Emre** to start looking at potential TLs
- want 2-3 lead by industry - recruitment opportunity for bioinformatics
- explain what a project is like, the scope, publications
- ad for RNA society - **Dec. 19th**

## Participants
- potentially charge ($100, $50?)

## Misc
- developing world fund proposal to bring to RNA Society
- Emre to contact Orca for computing
- RNAseq for professors workshop
  - how much expertise would be needed

## Recruitment
- Logistics (2) - food, location, random go gets 
- Sponsorship (2) 
- Participant applications (2)
- Volunteers
- [x] Artem to send it out 
- [x] Jenny to write roles out

**Comment by emreerhan** [comment]
Not sure how much time I can commit yet but very interested in helping organize! At minimum, you can count on me to organize compute resources with the GSC.

**Comment by ababaian** [comment]
Also if you know someone you think would be a good fit, send them the link : )

**Comment by jenjaelin** [comment]
As I said in person, I'm happy to help until I have to move away :)

**Comment by klgray25** [comment]
I won't be able to help out next year :(

It seems like there were a lot of people who said they would be available in the exit survey from hackseq19. Also a great many unusual comments in the free-form text box, including hang-over advice, several recipes (as requested), and observations about the granola bars.

**Comment by NoushinN** [comment]
I'll be happy to join online and do remote assistance (e.g. social media, etc). Loving the topic and would be interested in joining, co-leading, or leading a team

**Comment by sjackman** [comment]
Check in with 10x Genomics to see if they'd be interested in sponsoring. You can e-mail me, and I can put you in touch with the right person.

**Comment by ababaian** [comment]
We'll go with **Wednesday Nov 27th at 6pm** with the first meeting.

**Comment by jenjaelin** [comment]
Hey Artem... any chance we could meet earlier in the day or tomorrow? Idk
about everyone else, but I'm going to have a real difficult time getting
home after the meeting without transit Wednesday :x

**Comment by emreerhan** [comment]
Oh great point Jen. I can't make it to the meeting if the transit strike happens.

**Comment by lfunderburk** [comment]
Maybe we can setup an online meeting?

**Comment by lfunderburk** [comment]
We can use GoTo Meeting, Google Hang outs or Zoom. If people are open, I'd set it up and send a link to the meeting.

**Comment by ababaian** [comment]
If @emreerhan / @NoushinN can do Tuesday that would work. If not we can fall back to online meeting for those who can't make it given a transit strike. I would prefer not to use online meetings just so we can have an easier discussion but we'll have to be flexible with the transit strike.

**Comment by emreerhan** [comment]
Is Tuesday tomorrow? If so, I can do tomorrow at 6pm.

**Comment by NoushinN** [comment]
unfortunately, I can only make the online meeting..can follow up on proceeding notes if joining online isn't an option

**Comment by ababaian** [comment]
Let's do tomorrow, I'll send an email out in a bit.

**Comment by bfjia** [comment]
If it's tomorrow(Tues), can we do 5pm?






-------- Original message --------

**Comment by ababaian** [comment]
Email in case i missed you

> 
> Hey gang,
> 
> Time to get this ball rolling for the the creme-de-la-creme of hackseq! This is a fantastic opportunity to raise the international profile of hackseq, secure long-term levels of funding and spread the wings of our little hackathon collective. I'd also like to have a brief discussion afterwards about doing more to formalize hackseq as it's own institution and how we can help ensure long-term success.
> 
> We're meeting tomorrow, Tuesday Novermber 26th at 5:30 pm at the CRC. I look forward to meeting you all tomorrow.
> 
> We've moved the date up as per the issue discussion in case of transit strike. (https://github.com/hackseq/hackseqRNA/issues/1). I added a few people just in case you can make it and/or keep an eye on the issues to pop in expert feedback ;)
> 
> I'm stoked, let's make this exceptional!

![hackseq_logo](https://user-images.githubusercontent.com/9220907/69600702-81674400-1009-11ea-9134-89a7fa17388e.png)

**Comment by jenjaelin** [comment]
Wrote out a quick point form blurb of roles we're potentially still missing. I'm happy to take general coordinatior unless someone else wants to do it. Feel free to add to this if I missed something, otherwise, @ababaian I think you can send out the email

## Roles still needed (number of organizers):
### Logistics (2)

- nourishment coordinator
  - keeping track of attendee numbers, dietary restrictions
  - organizing coffee, snacks, meals
  - coordinating with venue and deliveries as needed
  - organize social (?)

- General Coordinator
  - supplies (pens, paper, power bars, signs, directions etc)
  - signs, posters etc for day of
  - scheduling (for event and other organizers)
  - in charge of making sure that day runs smoothly and everything is done on time/at the time

### Sponsorship (2) - working under/with Justin

- Sponsorship liaison
  - researching/contacting potential sponsors

- Treasurer
  - keep track of sponsorships as they come in
  - manage budget

### Participant applications (2)

  - organize and send out forms and applications to participants
  - lead participant sorting post applications
  - point of contact for participants with questions

**Comment by itsDagu** [comment]
I'd be happy to help with Sponsorship again!

**Comment by bfjia** [comment]
@itsDagu thanks for your interest. would you be willing to spearhead sponsorship for hackseqRNA?

**Comment by NoushinN** [comment]
Thanks for the notes @jenjaelin Happy to take up the participant applications role along with someone else, I believe this is a task that can be done remotely and I could travel to meet if need be.

**Comment by NoushinN** [comment]
> Email in case i missed you
> 
> > Hey gang,
> > Time to get this ball rolling for the the creme-de-la-creme of hackseq! This is a fantastic opportunity to raise the international profile of hackseq, secure long-term levels of funding and spread the wings of our little hackathon collective. I'd also like to have a brief discussion afterwards about doing more to formalize hackseq as it's own institution and how we can help ensure long-term success.
> > We're meeting tomorrow, Tuesday Novermber 26th at 5:30 pm at the CRC. I look forward to meeting you all tomorrow.
> > We've moved the date up as per the issue discussion in case of transit strike. (#1). I added a few people just in case you can make it and/or keep an eye on the issues to pop in expert feedback ;)
> > I'm stoked, let's make this exceptional!
> 
> ![hackseq_logo](https://user-images.githubusercontent.com/9220907/69600702-81674400-1009-11ea-9134-89a7fa17388e.png)

loving the logo! are we still generally operating under hackseq? same email/social median handles?

**Comment by ababaian** [comment]
Same everything, yeah. I'm working on a make-over for Twitter/ Website to rebrand for this event.

**Comment by sjackman** [comment]
@itsDagu Check in with 10x Genomics to see if they'd be interested in sponsoring. You can e-mail me, and I can put you in touch with the right person.
