### ISSUE TITLE
New year, New Org meeting! (#2)

### ISSUE THREAD

**Issue by ababaian** [hackseq/hackseqRNA#10]
Happy New Year @hackseq/hackseqrna_org!

It's officially the dystopian sci-fi future of 2020! Let's celebrate with some hackathon organization!

Please complete the [Online Poll](https://dudle.inf.tu-dresden.de/hsrna2/) for meeting times.

# Tentative Agenda
- Add All contact information for organizers in the PRIVATE readme

# Organizational Recruitment [ Artem ]
- Sent out hackseq email on new years. Sent to spam folders :  /
- Follow-up with targeted email to people who responded to hs19 survey

# Location Update [ Jen ]
- [  ] How much was the venue? 
## Ponderosa Ballroom
- booked Ponderosa Ballroom so we need to talk to whomever booked (hotel) room blocks at UBC for RNA2020 to talk about potentially extending them for the weekend that hackseqRNA is running.
- regards to that, let me know who that is so I can coordinate?
- we also probably need to book rooms in Ponderosa beyond the ballroom. that has to be done through UBC booking
- someone should go see the ballroom and adjoining rooms so we can get an idea of what rooms and how many rooms we need (this I can arrange but I would appreciate a 2nd person coming with me).

# Team Leader Recruitment
- Discuss possible merged team-lead / participant recruitment phase. Allow for more fluid movement of individuals per team. --> Confirm we will do this.
- Aim for 2-3 industry-led teams. Recruitment for bioinformatics.
- [ ] Participant Form online (Emre)
- [ ] Prepare email advertisment for email-lists (including RNA Society - Dec 12th.

## Webpage update
- [ ] Create updated webpage for team lead ( Alex  + Emre )
  - "Why should you run a project?"
  - "What is the scope of a successful project?"
  - "What did previous projects 'look' like?"
  - FAQ on team leads. Talk to previous team leads about relevant information to include.
  - Show off publications / testimonials
  - Have a human emphasis on website revamp

## Team Leader Recruitment
- [ ] Create a list of RNA team leaders to head-hunt, scout out people who will know and/or can suggest team leaders.
- [x] Pass previous RNA Society abstract book to Emre (Artem)

### Sponsorship Update
- [x] Draft of Sponsorship Plan on github
- [ ] Develop webpage for sponsorship information + hackseq selling information
- [x] Artem put Justin in touch with Stephen/Alain RE: sponsorship.

**Comment by ababaian** [comment]
Let's meet 5pm on Tuesday January 7th at the BCCRC (675 W 10th Ave).

**Comment by jenjaelin** [comment]
I'm an idiot and forgot to vote, but I'll be somewhere above Manitoba around that time. 

Things to talk about on my end: 
- booked Ponderosa Ballroom so we need to talk to whomever booked (hotel) room blocks at UBC for RNA2020 to talk about potentially extending them for the weekend that hackseqRNA is running.
  - regards to that, let me know who that is so I can coordinate?
- we also probably need to book rooms in Ponderosa beyond the ballroom. that has to be done through UBC booking
- someone should go see the ballroom and adjoining rooms so we can get an idea of what rooms and how many rooms we need (this I can arrange but I would appreciate a 2nd person coming with me).

Happy New Year everyone!

**Comment by bfjia** [comment]
I got a pretty hard cutoff of 6pm tomorrow evening. Lets talk about the proposed sponsorship package early please

**Comment by itsDagu** [comment]
Hey all, I won't be able to join in person but will be available on Skype for the meeting. Let me know when you guys are ready!

**Comment by ababaian** [comment]
I don't have good skype capabilities here but I'll add notes later tonight and we can chat some time tomorrow if that's OK.
