### ISSUE TITLE
Email Flyer

### ISSUE THREAD

**Issue by ababaian** [hackseq/hackseqRNA#15]
Hey @SweetiePi 

I've had this design idea for a bit to make an email flyer / poster out of. I put it together but I still think it's missing a little bit of a design element to tie it all together. Something like a sprite is needed. Do you have any suggestions and/or anything you think you can add to it?

We'll also need a short text description but I think wecan grab that off the mail-list.

[snes-seq_draft](https://user-images.githubusercontent.com/9220907/73706433-53c90600-46f0-11ea-83e8-e88faf9ecb28.png)

**Comment by alexsweeten** [comment]
Damn that looks so cool!

Possibly a final fantasy style battle with the boss being a pseudoknot or something?


![](https://lparchive.org/Final-Fantasy-V-Advance-(by-Dr-Pepper)/Update%2033/1-FF5UpdateSeventeen01.png)

**Comment by ababaian** [comment]
Actually a FF fight would be a super bad-ass visual as well to use for advertising lol! Have like pixelly A, T, G, C fighting that psueoknot =D

Take a look at some SNES packages, they almost never use in-game graphics :P

**Comment by ababaian** [comment]
It was missing a title. That's it!

#  Draft 1 - do not use. See below
[snes-seq_draf_2](https://user-images.githubusercontent.com/9220907/73780990-680c1200-4787-11ea-8361-1aad33a6b207.png)

------------------------------------------------------

Let me know if y'all have any edit suggestions.

Cheers!

**Comment by alexsweeten** [comment]
Has a Missingno vibe to it. I like it! ![image](https://user-images.githubusercontent.com/7028404/73782317-c369e000-4746-11ea-8516-f52b8746474e.png)

is this a general email or are we targeting this to potential team leads?

**Comment by ababaian** [comment]
Maybe adding a little bit of text to really encourage team leaders would be good, I think that's the weakest part of our ad-campaign at the moment.

**Comment by ababaian** [comment]
# hackseqRNA Email Flyer Version 1

![hackseqRNA_snes3](https://user-images.githubusercontent.com/9220907/73848950-faacbf80-4820-11ea-8729-c7f2107e28e0.png)

> **hackseqRNA** (May 22 - 24, 2020) is a co-operative hackathon, propose a project, recruit a team of interdisciplinary scientists and catalyze your computational RNA idea into a reality. Teams of ~4-8 will sprint for 72 hours to develop cutting-edge software, pioneer RNA analysis pipelines, and build digital infrastructure for future research.
> 
> This year we're collaborating with the 25th RNA Society Meeting to bring world-class RNA biologists and bioinformaticians to our most exciting hackathon yet. 
> 
> We are actively looking for Project Proposals, trainee-led teams encouraged. Participant applications are open.
> 
> Apply online today at https://www.hackseq.com (due: Feb 28, 2020).
> 
> **hackseqRNA Organizing Committee**
>

**Comment by ababaian** [comment]
@SweetiePi I was thinking last night. What about an art contest for hsRNA? We use the SNES/hackseqRNA template, the goal to design a video-game cover for bioinformatics. We could have one for like RNA-seq / ChIP-seq etc... Use real data in making the cover and make it look like 10 year old you would love to play that  game. Bioinformatics is pretty much grinding for XP anyways.

What do you think?

**Comment by alexsweeten** [comment]
I like the riboseq data a lot! Fits better within the grid.

Sounds like a neat idea. Would this contest go on during the hackathon, or would we advertise it beforehand?

**Comment by ababaian** [comment]
It might be too much 'work' to do during the hackathon but we could announce the winners at the hackathon.

**Comment by NoushinN** [comment]
is there anyone operating the twitter handle? do we have a social media post yet? 

> It was missing a title. That's it!
> 
> > **hackseqRNA** (May 22 - 24, 2020) is a co-operative hackathon, propose a project, recruit a team of interdisciplinary scientists and catalyze your computational RNA idea into a reality. Teams of ~4-8 will sprint for 72 hours to develop cutting-edge software, pioneer RNA analysis pipelines, and build digital infrastructure for future research.
> > This year we're collaborating with the 25th RNA Society Meeting to bring world-class RNA biologists and bioinformaticians to our most exciting hackathon yet.
> > We are actively looking for Project Proposals, trainee-led teams encouraged. Participant applications are open.
> > Apply online today at https://www.hackseq.com (due: Feb 28, 2020).
> 
> Let me know if y'all have any edit suggestions.
> 
> Cheers!

bizarre!! but pretty

**Comment by ababaian** [comment]
@baraaorabi are you still with vanbug? Do you think you could get this sent out to the mailing list this week?

**Comment by baraaorabi** [comment]
I am! I will let Ka Ming add this to our flyer before next VanBUG on the 20th. Also, do you want me to announce it in person then?

**Comment by baraaorabi** [comment]
@ababaian which graphic+description is the final version?

**Comment by ababaian** [comment]
The only one now on this page [here](https://github.com/hackseq/hackseqRNA/issues/15#issuecomment-582424654).

i've removed all draft images.

And Yes please advertise it at the next VanBug!
