### ISSUE TITLE
Extending application deadline?

### ISSUE THREAD

**Issue by emreerhan** [hackseq/hackseqRNA#17]
Hey everyone,

I think it may be a good idea to extend the deadline by a week or two. I've had someone express interest in submitting a team leader application, but they won't be able to do it by the deadline. What do you think?

**Comment by ababaian** [comment]
Yes let's do it. The RNA Society email hasn't gone out yet so I can still update it. March 13th?

The other option is we extend it closer to the date so people get their applications in and we have a better sense of the projects, else people will procrastinate. Maybe the day before we can extend it.

**Comment by ababaian** [comment]
Also it'll be important to close the first round of applications on Feb 28th so we can deal with travel grant business by those who applied by then.

**Comment by emreerhan** [comment]
Good call. Perhaps we should let people know that they'll only be guaranteed to be considered for travel grants if they apply by the first deadline.

**Comment by ababaian** [comment]
I kind of don't want to promote the travel grants until we know it's in hand

**Comment by emreerhan** [comment]
Did the RNA society email go out? We received 4 new applications of people going to the meeting who heard about us from "Mailing List" 🕺

**Comment by ababaian** [comment]
Yep it did this AM

**Comment by ababaian** [comment]
Maybe at the end of the work day today send out the team leader encouragement email to people signed up already.

Edit: and throw in that we're looking for organizers if you're local to Vancouver! ; )
