### ISSUE TITLE
Org Meeting 5 - Wednesday March 4th. 5:30pm BCCRC

### ISSUE THREAD

**Issue by ababaian** [hackseq/hackseqRNA#18]
### Date: Wednesday March 4th. 5:30pm BCCRC.
**Bring a friend:** To help kickstart `hackseq20` via @baraaorabi, we decided we'll all try to 'bring a friend' to the next organizing meeting to up our organizer numbers. So find a buddy who can help organize and drag them out :P

## Agenda
*Extend participant applications until March 13th* (Discuss)
Projects: 13 submissions
Participants: 92 applicants (lead incl.)

- [ ] Assign organizer to monitor the hackseq@gmail account

### Project Selection
- Project Selection Discussion (Emre)
- [x] Send follow-up confirmation email + book skype meetings

### Participant Recruitment
- Organizer to lead participant recruitment/assignment.
- Aim: 140 applicants for ~100 spots (?)
- [x] Send follow-up email to participants coming from abroad in first round applications that they are confirmed a spot at hackseqRNA while we sort out teams.
- [ ] Re-post on reddit and other social media platforms for participant applications. --> emphasize that if they go to RNA2020 they may qualify for a travel grant too.
- [ ] Promote participant recruitment on all previous channels.

### Sponsorship
- Updates on sponsorships... (Justin + co)
- [x] SJackman/10x update
- [x] Update on NSF Grant (Artem)
- [ ] Create a list of confirmed sponsors + tier on private repo
- [ ] Create new 'partners' page

### Venue
- [x] Confirm LSI Booking (Jen)
- [ ] Additional room bookings
- [x] Submit security form (Alex)
- [ ] Quote of final costs --> place doc on google drive
- Additional resources needed?

## Workshops
- Prof at UNBC asked to give ~1h workshop on graphlets to secure travel funds
- Discussion on having 'optional workshops' (git, AWS, etc...)

## hackseq20
- Baraa is initiating org-comm for hs20
- [ ] Email jen@ECOSCOPE for LSI booking/partnership (double-event sponsorship?)

## Previous Tasks
- [ ] @NoushinN can you take over the twitter account full time? This week it'll be important to be active to keep registrations going strong. Out last advertising push.

# Minutes
[hackseq Wiki](https://github.com/hackseq/hackseq18/wiki)
## Participants
- want about 140 people to pick
- how many reserved for from away
  - want to confirm this ASAP
- recruitment over the next 2 weeks
- sending out ads - twitter, reddit, facebook
- **Emre** to voluntell rest of team tasks

## Projects
- 13 thusfar 
  - merge 2
  - possibly 2-3 others?
- will interview all 
  - **Emre** to find question list and make sign up

## hackseq20
- Team? - how many people are organizers
- sponsorship now for 2 events
- **Baraa** to get in contact with **Jenny** and **Sasha** for venue booking (2 weekends on october)

## 5-year report
- publication for this hackseqRNA 
  - pre and post survey - expectations vs. experience
- types of questions - see issue #19 

## Misc
- Alex to take over hackseq gmail
- meme contest
- video game style RNA related sticker/ad
- doodle for approx Wed. 18th - **Jenny** to do doodle

**Comment by jenjaelin** [comment]
I can already say that I won't be able to make it unfortunately. I gotta fly out to Manitoba...

**Comment by ababaian** [comment]
if you have a biostars account; I posted about hackseqRNA to it, bump the post with an upvote to keep on it on the front page for a big today/this week [here](https://www.biostars.org/p/423744/)

**Comment by bfjia** [comment]
i wont be able to make it if its March 26-29. I'll be in Seattle for a conference.

**Comment by ababaian** [comment]
I was thinking we have this next week once we have the team leader applications received.

**Comment by bfjia** [comment]
ill be there then :). although i prefer a 5pm meeting.

**Comment by jenjaelin** [comment]
I can do next week after Tuesday :)

**Comment by ababaian** [comment]
Wed 4th, 5:30pm?

edit: changed to 30 minutes earlier (6 --> 5:30)

**Comment by bfjia** [comment]
anychance we can go 30min earlier please?

**Comment by baraaorabi** [comment]
Wed the 4th works! I do prefer 30min earlier too but i can manage

**Comment by ababaian** [comment]
@emreerhan Did you get a chance to send out the update email to the participants already signed up to encourage them to put a project forward?

**Comment by ababaian** [comment]
@emreerhan Did you get a chance to send out the update email to the participants already signed up to encourage them to put a project forward?

**Comment by emreerhan** [comment]
Oh shoot. I didnt! I'll do it as soon as I get in the office.

**Comment by emreerhan** [comment]
Oh shoot. I didnt! I'll do it as soon as I get in the office.

**Comment by emreerhan** [comment]
Check it out, there are 3 people who changed their applications to team leader applications

**Comment by zsteve** [comment]
Hey all, will there be a second round of applications? Just wondering before I try and blast departmental emails with shameless ads for signups.

**Comment by zsteve** [comment]
I assume the same also goes for team leader applications?

**Comment by ababaian** [comment]
TBH there's a lot more sign-ups then I anticipated for one round. I think we can extend participant applications and maybe team leader depending on how many projects come in. I think going in with 12 projects would be the ideal. You can always put that only the `Letter of intent` is required for the projects by Friday, people just need to submit their idea not have everything ready for it by Friday. This is a good idea to promote this week as people might think they're already too late.

**Comment by ababaian** [comment]
@jenjaelin @SweetiePi Is the venue stuff taken care of?

**Comment by jenjaelin** [comment]
Hey, I'm honestly drowning a little this week, but I will take care of it
tomorrow afternoon, and if not Friday at the latest.

**Comment by alexsweeten** [comment]
Contacted UBC security, will update when I get a response.

**Comment by zsteve** [comment]
> TBH there's a lot more sign-ups then I anticipated for one round. I think we can extend participant applications and maybe team leader depending on how many projects come in. I think going in with 12 projects would be the ideal. You can always put that only the `Letter of intent` is required for the projects by Friday, people just need to submit their idea not have everything ready for it by Friday. This is a good idea to promote this week as people might think they're already too late.

Ok I have a strong expression of interest from one of the new asst prof, their research is exactly (computational) RNA biology. They are also attending the RNA Soc meeting, but mentioned they are busy and it would take some time to formulate a quality project. I think this is a very good opportunity for us.

See my opened issue in the PRIVATE.

**Comment by ababaian** [comment]
Awesome @zsteve! The initial project submissions are more of a Letter of Intent, we can work with them once the basic idea is sketched out to optimize it for a hackathon.

**Comment by jenjaelin** [comment]
@SweetiePi I put in the form for security. Will forward it to you when it comes back

Custodial services have been confirmed

**Comment by alexsweeten** [comment]
@jenjaelin was it [this form](https://security.ubc.ca/node/83)?

**Comment by jenjaelin** [comment]
Yep

Jennifer Lin

**Comment by emreerhan** [comment]
Sent out emails to participants from abroad, and team leaders earlier today.

**Comment by alexsweeten** [comment]
I created a spreadsheet of interviews for potential team leads [here](https://docs.google.com/spreadsheets/d/1339hSbSsj-XMii389BqMARCiE5BShd9JWL5lvwmT5s4). Please assign yourself to at least 2. Once we get a reply from a team lead, I'll update the sheet with their availability.
