### ISSUE TITLE
Location Booking

### ISSUE THREAD

**Issue by ababaian** [hackseq/hackseqRNA#2]
**Finalize booking by** : Dec. 10th, 2019

Aim for ~90 people in total. 3-day booking.

## Inquire regarding location.
-  Check for Availability / Cost / Feasibility.
-  [x] SFU Harbour Centre Availability ( Justin )
-  [x] UBC Robson Square ( Jen )
- [x] Hotel booking ( Jen )
  - Four Seasons - contacted
  - Fairmont Vancouver - contacted

- [x] Connect Jen with Simple Meetings Organizer. (Artem)
- [ ] Confirm booking / funding with RNA society (Artem)

**Comment by jenjaelin** [comment]
@ababaian 

When you say Fairmont Vancouver, do you mean Waterfront, Pacific Rim or the Hotel Vancouver (yah apparently there's 3)? Or should I ask all 3?

**Comment by ababaian** [comment]
I was thinking Hotel Vancouver as it's a nice central location.

**Comment by jenjaelin** [comment]
Fairmont has a godawful website and contact info, I'll figure it out :P

**Comment by jenjaelin** [comment]
@ababaian do we know which hotel the conference is booking their attendees into?

**Comment by ababaian** [comment]
I sent you an email hooking you up with Mary from the RNA society organizing company.

**Comment by jenjaelin** [comment]
thanks! My lab also had a recent meeting and booking with Sheraton Wall so that might get us a good connection. Downside is that it is a little far.... I'll see what Fairmont says and same with Mary (thanks for doing that).

**Comment by jenjaelin** [comment]
what do y'all think about considering booking several classrooms/board rooms rather than a single atrium if we can't find something the size of LSI?

**Comment by ababaian** [comment]
hatching health does this, if we can book a whole wing and/or section of a building I think this would work, just keep people in generally the same locale.

**Comment by jenjaelin** [comment]
okay. In that case, I'll look into some locations at UBC... idk how much
it'll cost but will keep you posted.

J

**Comment by jenjaelin** [comment]
Haven't checked Robson Square yet, but I called and sent an email to UBC conferences and waiting to hear back on details for alternative locations at UBC.

**Comment by jenjaelin** [comment]
Also sent out a request to WeWork on a whim... lets see what they say.
