### ISSUE TITLE
Project information Request

### ISSUE THREAD

**Issue by ababaian** [hackseq/hackseqRNA#20]
For the website and to promote projects we'll need the following information for each project. Ideally we'd have these in hand going into the interviews.

1) Project Name (~1-2 words)
2) Title (75 characters max)
3) Project pitch. What is the core that makes this project interesting to join? (200 character max)
4) Recruiting Abstract. Overview of the main objectives, why they are significant and how you plan to accomplish it. (150 words max)
5) Keywords describing main skill requisites (upto 6)

Then we have optional requirements which will significantly aid in recruiting talented individuals to your project.

6) Logo / Social media image for the project.
7) Start Github page for the project and initialize a `README.md` with project overview.
8) Highly specialized skills for us to head-hunt participants to fill.

**Comment by emreerhan** [comment]
Let's collect these from the team leads after we have interviews with them.
