### ISSUE TITLE
COVID-19 contingency plan?

### ISSUE THREAD

**Issue by bfjia** [hackseq/hackseqRNA#24]
With all the travel restrictions currently in place by some major universities and other cancelled conferences, should we have a contingency plan for COVID19 related cancellations?

Our event is in May which will be at the end of the epidemic, but doesnt hurt to plan anyways.

**Comment by emreerhan** [comment]
I think we should stick to whatever the RNA Society decides to do. If they decide to postpone the conference, then perhaps we should also consider postponing hackseqRNA. If they decide to cancel the meeting all together--I think this is very unlikely--we can offer remote positions to everyone who was planning on travelling to Vancouver.

**Comment by alexsweeten** [comment]
We recieved a few emails about this yesterday and some people have swapped from in-person to remote attendance. Worst case we can have a completely remote hackathon as an option.

**Comment by ababaian** [comment]
My opinion is we should cancel, and so should the RNA Society. I think after March 15th, the RNA Society abstract deadline, they'll be able to make a clear decision with such low attendance. 

We should start putting together the contingency plan for a `digitally distributed hackseqRNA`. Organize several small (5-6 people) local clusters spread around the world, find local leaders to book the room and get the wifi, and still have an 'event' just distributed over many centers. It'll take some planning : )

**Comment by bfjia** [comment]
they postponed bigx :O

**Comment by ababaian** [comment]
Man shit just hit the fan, trump is stopping all flights from Europe for 30 days.

**Comment by bfjia** [comment]
yupppp. and my comment about the epidemic was shortlived. it's now an pandemic.
Honestly, lets see what RNA society says. 
for now,  @jenjaelin how would cancelling the venue work?

**Comment by jenjaelin** [comment]
I have a feeling we can just cancel given we haven’t put any money down. I also think given what’s going on, they prolly won’t charge us. But I can get back to you on that. 

So we definitely cancelling?

**Comment by ababaian** [comment]
Not yet, but yeah I think re-formatting is going to be the move.

**Comment by alexsweeten** [comment]
Since many of the potential team leads are expecting to get interviewed next week, I'm going to e-mail them a heads up and postpone interviews for now until we figure out an alternative.

**Comment by ababaian** [comment]
I would say let's go ahead with the interviews and discuss this with them.

**Comment by ababaian** [comment]
> “Effective today, we also directing all event organizers to cancel any gathering larger than 250 people. This includes indoor and outdoor sporting events, conferences, meetings, religious gatherings or other similar events. This threshold has been selected, as it is much easier to maintain important social distancing to prevent transmission of COVID-19."

Source: [BC Gov](https://news.gov.bc.ca/releases/2020HLTH0077-000484)

I think we can for sure call it. I'd let RNA Society make there announcement first and we can discuss the plan of action next week. How does webcam conference calls sound for everyone?

**Comment by bfjia** [comment]
Fine with me. Things went really south in the past week.

**Comment by ababaian** [comment]
The writing is on the wall, I think people just needed a little bit of time to emotionally catch up to the reality.

**Comment by jenjaelin** [comment]
I got our LSI booking released. unless you guys want me to retract that?

**Comment by ababaian** [comment]
Let's all hang tight till Monday before we do anything. I think it should be OK to release LSI for a couple of days.

**Comment by jenjaelin** [comment]
Yah I don’t think anyone is going to book it out from underneath us at this point.  If we need to I’ll tell them I changed my mind on Monday. 

J

**Comment by ababaian** [comment]
See #23
