### ISSUE TITLE
Organizational meeting: Let's regroup - Friday March 20th 5:30pm

### ISSUE THREAD

**Issue by jenjaelin** [hackseq/hackseqRNA#25]
Let's virtually meet up on Friday and figure some things out. 

Could someone make a zoom meeting again?

# Minutes

## General planning
- RNA meeting cancelled - e-meeting now

### Website
- [blurb for explaining ultra-hackathon](https://docs.google.com/document/d/1PTaQoxOwyWO8hATq7aRKIB4VydUnPmliyVDrRNh56xM/edit?usp=sharing) 
  - everyone take a look at this

### Bioinformatics for good
- roster for researchers to take a look at to find people who may be able to help
- google form/spreadsheet for projects
- think of getting interested team leads to add to this
- subdomain? - hackseq.com/bioinformaticsforgood (?)
  - **Artem** to help **Lisa** to set up

### Methodology
- promote any relevant hackathons? - list them 
- potentially reach out to try to centralize projects/hackathons as a repo
- how to inventory hackathons - sort out dates
  - **Tayab** to head initial search

### Team leads
- guide for onboarding sprints, leading a remote project
- how to restructure - **Artem** and **Lisa** to ask **Laura**? 
- finish team lead interviews

## For Monday
- [ ]  draft email for mailing lists
- [ ] Website explanation 
- [ ] form for project submission

**Comment by emreerhan** [comment]
Emre Erhan is inviting you to a scheduled Zoom meeting.

Topic: hackseqRNA: COVID-19 Ultra Hackathon
Time: Mar 20, 2020 05:30 PM Vancouver

Join Zoom Meeting
https://zoom.us/j/520932914

Meeting ID: 520 932 914

One tap mobile
,,520932914# US Toll

Dial by your location
         US Toll
        
Meeting ID: 520 932 914
Find your local number: https://zoom.us/u/actDrYpAfo
