### ISSUE TITLE
Team Leader Recuritment

### ISSUE THREAD

**Issue by ababaian** [hackseq/hackseqRNA#3]
**Recruitment open and in full swing by**: Dec. 10th 2019

- Aim for 2-3 industry-led teams. Recruitment for bioinformatics.
- [x] Prepare email advertisment for email-lists (including RNA Society - Dec 12th.

## Webpage update
- [x] Create updated webpage for team lead ( Alex )
  - "Why should you run a project?"
  - "What is the scope of a successful project?"
  - "What did previous projects 'look' like?"
  - FAQ on team leads. Talk to previous team leads about relevant information to include.
  - Show off publications / testimonials
  - Have a human emphasis on website revamp

## Team Lead Application form
- [x] Form online (Emre) 

## Team Leader Recruitment
- [x] Create a list of RNA team leaders to head-hunt, scout out people who will know and/or can suggest team leaders.
- [x] Pass previous RNA Society abstract book to Emre (Artem)

**Comment by emreerhan** [comment]
Hey @ababaian , could you send me the abstract book when you get a chance?

**Comment by ababaian** [comment]
It's on the Google Drive under `Teams`

**Comment by emreerhan** [comment]
Some updates:
- I have a contact who is a part of the IRB COSI (https://irbgroup.org/) who is happy to distribute information about the hackseq both on the IRB website, on their mailing list, and through their network.
- My colleague at the GSC is well connected with those in the RNA secondary structure prediction world. He's going to connect me with the people who are behind the ViennaRNA package.


To do:
- Go through Artem's abstract book
- Contact some industry people
- Start creating a list of potential team leaders

**Comment by emreerhan** [comment]
I won't be able to do this until next week because of final exams and projects.

**Comment by ababaian** [comment]
Baby dropped, I'm going to be a little busy next couple of days to help out with this stuff guys.

**Comment by alexsweeten** [comment]
Congratulations!

**Comment by jenjaelin** [comment]
Congrats on your new +1 :D and my condolences for your impending lack of sleep

**Comment by bfjia** [comment]
Congratulations!!!

**Comment by emreerhan** [comment]
Wow! Congrats Artem.
