### ISSUE TITLE
sponsorship + private repo?

### ISSUE THREAD

**Issue by bfjia** [hackseq/hackseqRNA#5]
More to come...

**Comment by jenjaelin** [comment]
do we have a private repo yet?

**Comment by bfjia** [comment]
Not yet. It seems like i dont have permission to create repos wtf.. @ababaian  can you take over?

**Comment by ababaian** [comment]
I made a private repo, weird you can't do this tho

**Comment by bfjia** [comment]
thanks! 
yeahh. maybe its a phone thing.
