### ISSUE TITLE
UBC Rental Space - Ponderosa Ballroom

### ISSUE THREAD

**Issue by jenjaelin** [hackseq/hackseqRNA#8]
To Check:

- [x] Robson Square
  - contacted
  - response - rooms are booked for the date we want
- [x] Ponderosa ballroom
 - contacted
 - received response - temporary hold on room
- [x] Alumni Centre
  - contacted - booked for the dates
- [x] Nest
  - contacted
  - received response - booked for the date we want
- [ ] Pharm Sci
  - contacted
- [ ] Forestry
  - contacted
---
Hey y'all, heard back from UBC Hospitality:

Hi Jennifer,
 
During the summer, our priority is for conferences with meeting space and accommodation together. **For meeting space only, we can put it on tentative hold now and confirm it 8 weeks in advance. If you think some people will need to stay on campus during the competition, we can definitely contract & confirm the space right away.**
 
We do have the Ponderosa ballroom available for your dates. Rates & Spec sheet attached.
The rate includes the AV, tables & chairs, linen and set up/takedown. There are several classrooms in Ponderosa that can be used as breakout rooms. Request for classrooms must go through scheduling services in January and will be approved based on availability. If you prefer to use Forest Sciences lecture halls, you will also need to go through scheduling services and through the FSC to book the atrium if you need it.
 
The Robert Lee Alumni Centre and the Nest will also be suitable for your event. They are spate entities and you will need to reach out to them direct.
 
---
What do you guys think? The main thing is if we can secure people staying on campus, then we can book now, otherwise it is a tentative until 8 weeks prior. I can also inquire about the Alumni Centre and the Nest.

**Comment by jenjaelin** [comment]
attachments:

[Ponderosa Mtg Space 2020 Rates - UBC INTERNAL.pd](https://github.com/hackseq/hackseqRNA/files/3928930/Ponderosa.Mtg.Space.2020.Rates.-.UBC.INTERNAL.pdf)
![Pond Ballroom Banquet Style](https://user-images.githubusercontent.com/37309499/70270872-1aa8ff80-175a-11ea-8668-ef091ed91eac.jpg)

**Comment by ababaian** [comment]
Nest doesn't have a nice room for this, there's no windows in the room big enough to fit. The Ponderosa room doesn't look too hot either but we could make it work. How about Alumni Centre?

**Comment by jenjaelin** [comment]
Had a call with Amira (events and bookings) and I temporarily put a hold on the Ponderosa as we talk it out. A few new things:

- since we have a room block for the RNA 2020, they can give us a firm booking and also book extra lecture rooms as we want for us through UBC afterwards.
- all the venues mentioned require catering to be done through their approved list (The list is larger for the Alumni centre). For Ponderosa it needs to be [Scholar catering](https://www.catering.ubc.ca/), for the Nest through AMS.

I'll reach out to the alumni centre and see what they've got.

**Comment by jenjaelin** [comment]
Robson Square:
----
Hi Jennifer,
 
Thank you for your booking inquiry!
 
Unfortunately the C150/180 is not available on May 22nd-24th, 2020. However, we have other rooms that could potentially work for your event:
 
- HSBC Hall: can fit up to 40 people in pods.
- Room C400: can fit up to 30 people in pods.
- Room C485: can fit up to 30 people in pods.
 
The above rooms are currently on hold for another event on May 22-24, but I will let you know by next Tuesday if these holds get confirmed or released.
 
As for the larger amphitheater, our Theater might be available on May 22-23 (also currently on hold), but it is not available on May 24.
 
Catering. We have an exclusive contract with Peake of Catering, so any food or beverages served must be ordered from our menu, or a penalty will apply. Attached is our current menu options.
 
AV & Technician: Included in the room rental are: complimentary wireless internet, a projection screen, and whiteboards. Additional AV equipment (ex. power bars, mics, etc.) is available for a rental cost, or you are welcome to bring in your own equipment. Ceiling-mounted projector is available for $250.00/day. Tech support can be arranged at $55/hour (min 4 hours).

----

seems like the common thread here is that we are going to have a lot less flexibility with food orders.

Also, Alumni centre is booked for the dates. They forwarded me onto the Nest.

**Comment by ababaian** [comment]
D: This is looking to be a bit more challenging then I thought.

**Comment by jenjaelin** [comment]
Yep. It looks like we will have to cave a bit on catering or keep looking for places that just rent out space. 

----
Robson Square got back to me: 

Hi Jennifer,
 
Please find attached the room rental quote for HSBC Hall, C485 and C400 for three days. May I ask if the payment will be made via UBC speedchart or UBC JV? If so, we would be happy to offer 30% discount on the room rental. Please let me know and I will then send you a revised quote.
 
Unfortunately, our catering policies are very strict due to the exclusivity agreement that we have with Peake of Catering. The following penalty would be applied: $10/per attendee + amount equivalent to the total amount of the room rental. Attendees are welcome to bring their own food for personal consumption. However external catering (arranged either through the organizer or an attendee) is against policy. For example, this includes the orders such as coffee travelers from Starbucks, box of pastries from Tim Hortons, snacks from any other catering company/café/grocery stores etc.
 
The HSBC hall, C400 and C485 are currently on hold for another event on May 22-24, but I will let you know by next Tuesday (December 10) if these holds get confirmed or released.

 ----

Price is in and around $7000 for the 3 days not including catering.

**Comment by ababaian** [comment]
We could probably use a UBC speedchart from MEDG if we agree to transfer them the funds first so that's less 30% at least. Yeah looks like UBC really boxes in on the catering which would be challenging to pull off with feeding people for the duration. Tough choices.

**Comment by jenjaelin** [comment]
Also heard back from the Nest, they're only available on May 22, and WeWork is possibly available on the weekend. that may give us a little more freedom...

...nevermind, they don't do weekends currently. So basically our current options are Robson or Ponderosa. Amira said she's willing to look the other way for snacks at Ponderosa if we order meals through their catering contract. Robson is a lot more strict.

We can also keep looking and I can inquire into the Forestry Building
