### ISSUE TITLE
Org recruit

### ISSUE THREAD

**Issue by baraaorabi** [hackseq/hackseqRNA#9]
Hey @ababaian 

My friend @mariamarab is interesting in joining the org team for hackseqRNA. She's been a participant in hackseq18/19. I wanted to tag her for the first meeting but I forgot to. Are there org roles that are still open in hackseqRNA team?

**Comment by jenjaelin** [comment]
Definitely still spots left :) namely Logistics, participant apps and Finance related things

**Comment by ababaian** [comment]
Let's get this email out on Monday. I'll have this drafted and ready to send the mailing list. This legit slipped my mind.

**Comment by ababaian** [comment]
@mariamarab, we're meeting this Tuesday at 5pm at the BCCRC. Can you make it?

**Comment by mariamarab** [comment]
Sorry, I can’t make it tomorrow before 6:30. Will the meetings always be at that time?

**Comment by ababaian** [comment]
We usually send out a poll beforehand so it varies. I'll remember to ping you before the next one so you can vote.
